### PR TITLE
Add Toasts for the save and copy buttons & fix positioning

### LINKED ISSUE #55: Toasts do not scroll with window
They are fixed at the bottom-right corner of the view pane when the page is scrolled up, but they do not scroll with the view pane.

### LINKED ISSUE #60: Use an auto-dismissing Toast instead of an alert() when saving messages

### LINKED ISSUE #70: Add a toast when copying preview link
Currently there is no indication that anything happened.

### PR DESCRIPTION
**Pull request by AllegroFox**
Fixes #55 
Fixes #60 
Fixes #70

### CODE REVIEW

File: src/components/Toasts.tsx [hunk 1]
```diff
@@ -29,7 +34,7 @@ function Toasts() {
   ));
 
   return (
-    <ToastContainer position="bottom-end" className="me-2 mb-2">
+    <ToastContainer position="bottom-end" className="me-2 mb-2 position-fixed">
```
Comment (brennie) [inline src/components/Toasts.tsx:37]: Use `containerPosition="fixed"` ([docs](https://react-bootstrap.github.io/components/toasts/#toast-container-props))

File: src/hooks/useToasts.ts [hunk 2]
```diff
@@ -11,11 +11,18 @@ export interface Toast {
   id: string;
   title: string;
   body: ToastBody;
+  autohide?: boolean;
+  delay?: number;
```
Comment (brennie) [inline src/hooks/useToasts.ts:15]: I think we should always use the same delay for auto-hiding notifications. Make that a const in Toasts and only provide the `autohide?` parameter.

File: src/hooks/useToasts.ts [hunk 3]
```diff
@@ -24,16 +31,21 @@ export const ToastsContext = createContext<UseToasts>({} as UseToasts);
...
-      ...oldToasts,
-      {
-        id: window.crypto.randomUUID(),
-        title,
-        body,
-      },
-    ]);
-  }, []);
+  const addToast = useCallback(
+    (title: string, body: ToastBody, autohide?: boolean, delay?: number) => {
```
Comment (brennie) [inline src/hooks/useToasts.ts:35]: Prefer avoiding boolean args, as seeing true or false in a function call doesn't tell you much without looking at the function call definition.

How about:
```ts
addToast(
  title: string,
  body: ToastBody,
  { autohide = false }: { autohide?: boolean } = {}
)
```

**Review by brennie — APPROVED** [review]
